services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Hamstah\Adventskalender\:
    resource: '../Classes/*'
    public: true

  Hamstah\Adventskalender\Dashboard\DoorWidget:
    public: true
    tags:
      - name: dashboard.widget
        identifier: 'adventskalender_door_widget'
        title: 'LLL:EXT:adventskalender/Resources/Private/Language/locallang_db.xlf:dashboard.widget.door.title'
        description: 'LLL:EXT:adventskalender/Resources/Private/Language/locallang_db.xlf:dashboard.widget.door.description'
        iconIdentifier: 'module-adventskalender'
        groupNames: 'adventskalender,general'
        height: 'medium'
        width: 'medium'
