services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Hamstah\Adventskalender\:
    resource: '../Classes/*'

  Hamstah\Adventskalender\Controller\:
    resource: '../Classes/Controller'
    tags: ['controller.argument_value_mapper']
